apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  type: LoadBalancer
  ports:
    - name: demo-app
      protocol: TCP
      port: 32000
      targetPort: 8080
      nodePort: 30000
